cpio: fix minor rust compiler warning
warning: call to `.clone()` on a reference in this situation does
nothing
   --> src/main.rs:289:27
    |
289 |     let mut outpath = path.clone();
    |                           ^^^^^^^^
    |
    = note: the type `Path` does not implement `Clone`, so calling
`clone` on `&Path` copies the reference, which does not do anything and
can be removed
    = note: `#[warn(noop_method_call)]` on by default
help: remove this redundant call
    |
289 -     let mut outpath = path.clone();
289 +     let mut outpath = path;

Signed-off-by: David Disseldorp <ddiss@suse.de>